dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="unicoq"
  matrix:
  - COQ_IMAGE="coqorg/coq:8.14"

# As described on https://bors.tech/documentation/getting-started/ we need a
# `staging` and a `trying` branch, both of which need to be CI-enabled.
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests. But bors will not see that travis already built it, so it's kinda useless
    # - master
    # (Left commented out until we find that it would be useful to enable)
    # We want to have CI for all master branches that target specific coq versions.
    - /master-.*/

install: |
  # Prepare the COQ container
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  travis_wait docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    export OPAMJOBS="2"
    set -ex  # -e = exit on failure; -x = trace for debug
    opam config list
    opam repo list
    opam list
    opam update default
    coqc --version
    opam list
    "
script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    coq_makefile -f _CoqProject -o Makefile
    make
    "
- docker stop COQ  # optional
- echo -en 'travis_fold:end:script\\r'
